### PR TITLE
add fillWithExpected property

### PR DESCRIPTION
**Pull request by rafaelcorradini**

### CODE REVIEW

**Comment by rafaelcorradini** [comment]
#7

**Comment by rafaelcorradini** [comment]
@ekzGuille Could you review the PR , please? Check if is that what you need.

**Comment by ekzGuille** [comment]
Hi, I've made a component if you want to test the functionallity because it is happening the same behaviour that when I made the tests and tried to add the flag by myself. (We made the same approach indeed)

```ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';

@Component({
  selector: 'components-preview',
  template: `
  <form [formGroup]="testFormInput">
    <h6>Mask: {{ PHONE_MASK }} | Replacer: {{ PHONE_MASK_REPLACER | json }} | fillWithExpected: {{ !fillWithExpected }} </h6>
    <ion-input
      formControlName="testInput"
      placeholder="{{PHONE_MASK}}"
      type="text"
      [simpleMask]="PHONE_MASK"
      [fillWithExpected]="!fillWithExpected"
      [newPatterns]="PHONE_MASK_REPLACER"
    ></ion-input>
    <small> When typing 3 writes (+3 </small>
    <small> When typing 9 writes (+39 </small>

    <h6>Mask: {{ PHONE_MASK }} | Replacer: {{ PHONE_MASK_REPLACER | json }} | fillWithExpected: {{ fillWithExpected }} </h6>
    <ion-input
      formControlName="testInput2"
      placeholder="{{PHONE_MASK}}"
      type="text"
      [simpleMask]="PHONE_MASK"
      [fillWithExpected]="fillWithExpected"
      [newPatterns]="PHONE_MASK_REPLACER"
    ></ion-input>
    <small> When typing 3 it should write (+39) 3 </small>
    <small> When typing 9 it should write (+39) 9 </small>
  </form>
`,
  styles: ['form { width: 60%; margin: 0 auto; padding: 2rem; } small { display: block; } h6 { margin: 2rem 0 0 0; } ion-input { border: 1px solid grey; }'],
})
export class ComponentsPreviewPage implements OnInit {

  constructor(private readonly formBuilder: FormBuilder) { }
  PHONE_MASK = '(+39) 000 000 000';
  PHONE_MASK_REPLACER = { '0': '[0-9]' };
  fillWithExpected = true;
  testFormInput: FormGroup;

  ngOnInit() {
    this.testFormInput = this.formBuilder.group({
      testInput: [''],
      testInput2: [''],
    });
  }
}
```

Angular version I'm using

```sh
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.1.7
Node: 12.18.4
OS: linux x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1001.7
@angular-devkit/build-angular      0.1001.7
@angular-devkit/core               10.1.7
@angular-devkit/schematics         10.1.7
@angular/cdk                       10.2.7
@angular/cli                       10.1.7
@angular/fire                      6.1.4
@angular/http                      7.2.16
@angular/material                  10.2.7
@angular/material-moment-adapter   11.2.1
@schematics/angular                10.1.7
@schematics/update                 0.1001.7
rxjs                               6.6.3
typescript                         4.0.2
```
Here is a example of the behaviour I'm facing

mask

With the flag, once you write on the *masked* part, you cannot write any more or even delete (only if you select the text)

**Comment by rafaelcorradini** [comment]
I've tried another approach this time. I believe this will work for you case.

**Comment by ekzGuille** [comment]
Yeah! I've tested it and It seems to work for me.
I know it's a tricky problem what I proposed. 

Thank you very much. Keep it up!

**Pull request merged**
